# Generated by Django 4.2.8 on 2023-12-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('type_of_instrument', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='date_of_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
